version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: markethub_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: markethub_db
      MYSQL_USER: markethub
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: